### ISSUE TITLE
Question about the variables

### ISSUE THREAD

**Issue by abeyaert** [duggabe/gr-morse-code-gen#2]
Hello,

I am quite a beginner with GNU Radio and working on a project with a similar input (vector of bits) but that are predetermined and to be further transmitted with FM modulation. 

I have seen that most of the variables are related to the Morse code transmission with the words per minute, however I was wondering about how to tune the interpolation rate of the Repeat for a known bit sequence, but out of the Morse standard. I would also expect some kind of periodic signal, if not an audio signal, at the input of the FM transmitter. What would you expect as a clean signal at the audio sink of your flowgraph in that case ?

I am also wondering about how you settled the cut off frequency and transition width of the low pass filter, at the output of the UCHar to Float block. Is it by hand, or is there a relationship with the previous variables ? 

Thanks for your feedback!

Anthony

**Comment by duggabe** [comment]
To answer your questions, here are some references:
* https://wiki.gnuradio.org/index.php/Tutorials
* https://wiki.gnuradio.org/index.php/Sample_Rate_Tutorial#Sink_hardware_example

1) Morse Code is an on-off keying. The vectors represent each dot bit time as a 1 and each space bit time as a 0. To transmit this data, the RF carrier is turned on and off with these vectors. In the example, the Signal Source block simulates the RF carrier and the Multiply block keys it on and off. Note that in my github link I have revised the filter to create a better keying waveshape.

2) Study the Tutorials and the Sample Rate Tutorial in particular to get a better understanding of setting sample rates.

3) Now to address your desire to translate vectors into FM, I am guessing that you are looking at RadioTeletype (RTTY). To do that, or a similar application, you must key two frequencies with the vectors. For RTTY, the standard tones are 2295 for Mark (1) and 2125 for Space (0). There are various modulator blocks to use, or you could use a "brute force" method with two signal sources.

GNU Radio allows you to experiment with various arrangements easily. So study the Tutorials and try things out!

Note for other readers: this question was asked on https://lists.gnu.org/archive/html/discuss-gnuradio/2020-07/msg00014.html
