### ISSUE TITLE
 Using gr-morse-code-gen/epy_block_0_0.py / for vector stream

### ISSUE THREAD

**Issue by lceans** [duggabe/gr-morse-code-gen#3]
Hi, I came across this code for your python block. Essentially, my application is taking a User Input ASCII message and converting the message to binary and output a vector and for now I just want to connect to scope sync to see the bit changes. So far I am a little stuck on the output portion of this. I see you did something similar in your code. Also I am new to python and coding in general but can you give me some tips on how you made the output function similarly to the vector source?

**Comment by duggabe** [comment]
what is the source of your user input? is it the terminal 'stdin' or a text file?
if all you want is to unpack the bits, you can use https://wiki.gnuradio.org/index.php/Unpack_K_Bits and not have python code at all.

**Comment by lceans** [comment]
> what is the source of your user input? is it the terminal 'stdin' or a text file?
> if all you want is to unpack the bits, you can use https://wiki.gnuradio.org/index.php/Unpack_K_Bits and not have python code at all.

So essentially my block has an input parameter called message where I can enter "Hello World" for example. This is then converted into binary. I want this binary to then be output of the block like the vector source.  

I did some experimenting with your code at the end where you are assigning output_items to get the output to function like this and it worked successfully on GRC 3.7.13.5 but my issue is I need to get this to work on an older system which runs GRC 3.7.11. Is there anything you did when assigning the outputs_items that causes an issue to not work between two versions

**Comment by duggabe** [comment]
I have very little experience with 3.7 and do not have a system to test with. A question like this is better suited for the gnuradio mailing list. See https://wiki.gnuradio.org/index.php/MailingLists
Also you can try the Matrix General Chat room:
* server: https://chat.gnuradio.org
* or via the Homeserver in a matrix app: gnuradio.matrix.ungleich.cloud
* room: #gnuradio:gnuradio.org

**Comment by lceans** [comment]
Appreciate the help thank!
