### ISSUE TITLE
decoder grc

### ISSUE THREAD

**Issue by leeyuxi** [duggabe/gr-morse-code-gen#6]
Hello, do you have designed the morse code decode? I designed this part meet some chanllenges, I need help.

**Comment by duggabe** [comment]
I have not attempted the morse code decode. If you do a search, you may find some others who have done so.

**Comment by dd0vs** [comment]
All,

i believe, that CW decoding is not trivial, you can check:

1.	CW-skimmer
2.	CW – get
3.	Fldigi (runs under Linux and W)

Regards aka vy73

Harald

DD0VS

 

 

Von: duggabe ***@***.***> 
Gesendet: Dienstag, 25. Mai 2021 21:33
An: duggabe/gr-morse-code-gen ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [duggabe/gr-morse-code-gen] decoder grc (#6)

 

I have not attempted the morse code decode. If you do a search, you may find some others who have done so.

**Comment by leeyuxi** [comment]
ok, thanks for your help!
